cmake_minimum_required(VERSION 4.2)
project(Lab6_2025_1)

set(CMAKE_CXX_STANDARD 20)

add_executable(Lab6_2025_1 main.cpp
        Bibliotecas/Infraccion.cpp
        Bibliotecas/Infraccion.h
        Bibliotecas/Empresa.cpp
        Bibliotecas/Empresa.h
        Bibliotecas/Multa.cpp
        Bibliotecas/Multa.h
        Bibliotecas/MinisterioDeTransporte.cpp
        Bibliotecas/MinisterioDeTransporte.h)
