cmake_minimum_required(VERSION 4.2)
project(Lab5_2025_2)

set(CMAKE_CXX_STANDARD 20)

add_executable(Lab5_2025_2 main.cpp
        Biblioteca/Streamer.cpp
        Biblioteca/Streamer.h
        Biblioteca/Funciones.cpp
        Biblioteca/Funciones.h
        Biblioteca/Gestor.cpp
        Biblioteca/Gestor.h)
